# base.yml
name: Build Base Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: harbor.lionswerk.com/lionswerk/crm/backend # backend of django-crm
      TAG: 0.0.1 #1.0.0

      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        with:
          ref: 'main'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: harbor.lionswerk.com
          username: ${{ secrets.DOCKER_HUB_USERNAME1 }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN1 }}
          
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: ${{env.IMG_NAME}}:${{env.TAG}}
